### ISSUE TITLE
Pulling currently results in an error (dNu #isAddition)

### ISSUE THREAD

**Issue by codeZeilen** [LeonBein/SmalltalkGitTesting#18]
SecurityManager state:
Restricted: false
FileAccess: true
SocketAccess: true
Working Dir C:\Users\patri\Desktop\aNewHome
Trusted Dir C:\Users\patri\Desktop\aNewHome\patri
Untrusted Dir C:\Users\patri\Documents\My Squeak

LBGitFileListDiff(Object)>>doesNotUnderstand: #isAddition
	Receiver: a LBGitFileListDiff
	Arguments and temporary variables: 
		aMessage: 	isAddition
		exception: 	MessageNotUnderstood: LBGitFileListDiff>>isAddition
		resumeValue: 	nil
	Receiver's instance variables: 
		left: 	a LBGitRecordedFilesArtifact(On commit: 'Adds new test cases for the obje...etc...
		right: 	a LBGitRecordedFilesArtifact(On commit: 'Adds object editor to readme [c...etc...
		added: 	#()
		removed: 	#()
		stayed: 	#('repository/.filetree' 'scripts/build_images.sh' '.travis.yml' 'scrip...etc...
		modified: 	#('README.md')
		diffs: 	(a LBGitFileModification)
		target: 	nil

SquotPatchBuilder>>addDiff:
	Receiver: a SquotPatchBuilder
	Arguments and temporary variables: 
		aDiff: 	a LBGitFileListDiff
	Receiver's instance variables: 
		diffs: 	(''->a LBGitFileListDiff )
		leftArtifacts: 	(''->a LBGitRecordedFilesArtifact(On commit: 'Adds new test case...etc...
		rightArtifacts: 	nil
		originalLoadOrder: 	('repository/Home.package' 'repository/BaselineOfHome.packag...etc...
		patchedLoadOrder: 	('repository/Home.package' 'repository/BaselineOfHome.package...etc...
		loadOrderDiff: 	nil

SquotPatchBuilder>>diffPath:from:to:
	Receiver: a SquotPatchBuilder
	Arguments and temporary variables: 
		path: 	''
		leftObjectContainer: 	a SquotSnapshot
		rightObjectContainer: 	a SquotSnapshot
	Receiver's instance variables: 
		diffs: 	(''->a LBGitFileListDiff )
		leftArtifacts: 	(''->a LBGitRecordedFilesArtifact(On commit: 'Adds new test case...etc...
		rightArtifacts: 	nil
		originalLoadOrder: 	('repository/Home.package' 'repository/BaselineOfHome.packag...etc...
		patchedLoadOrder: 	('repository/Home.package' 'repository/BaselineOfHome.package...etc...
		loadOrderDiff: 	nil

[] in SquitVersion>>patchRelativeToBaseVersion:
	Receiver: commit e2d1828 "Adds object editor to readme [ci skip]"
	Arguments and temporary variables: 
<<error during printing>
	Receiver's instance variables: 
		repository: 	a SquitRepository
		commit: 	a GitCommit('Adds object editor to readme [ci skip]')

Array(SequenceableCollection)>>do:
	Receiver: #('')
	Arguments and temporary variables: 
		aBlock: 	[closure] in SquitVersion>>patchRelativeToBaseVersion:
		index: 	1
		indexLimiT: 	1
	Receiver's instance variables: 
#('')

SquitVersion>>patchRelativeToBaseVersion:
	Receiver: commit e2d1828 "Adds object editor to readme [ci skip]"
	Arguments and temporary variables: 
		baseSquitVersion: 	commit d1c314a "Adds new test cases for the object editor and...etc...
		diff: 	(FSPath * 'README.md'->a GitDiffTreeEntry FSPath workingDirectory->a GitDiffTreeEntry...etc...
		changedPaths: 	#('' 'README.md')
		mySnapshot: 	a SquotSnapshot
		baseSnapshot: 	a SquotSnapshot
		myChangedArtifactPaths: 	#('')
		baseChangedArtifactPaths: 	#('')
		deletedPaths: 	#()
		patchBuilder: 	a SquotPatchBuilder
	Receiver's instance variables: 
		repository: 	a SquitRepository
		commit: 	a GitCommit('Adds object editor to readme [ci skip]')

SquitVersion>>patchRelativeToBase:
	Receiver: commit e2d1828 "Adds object editor to readme [ci skip]"
	Arguments and temporary variables: 
		objectContainer: 	commit d1c314a "Adds new test cases for the object editor and ...etc...
	Receiver's instance variables: 
		repository: 	a SquitRepository
		commit: 	a GitCommit('Adds object editor to readme [ci skip]')

SquotMergePatchBuilder>>patchFrom:to:base:
	Receiver: a SquotMergePatchBuilder
	Arguments and temporary variables: 
		leftObjectContainer: 	a SquotSnapshot
		rightObjectContainer: 	commit e2d1828 "Adds object editor to readme [ci skip]"
		baseObjectContainer: 	commit d1c314a "Adds new test cases for the object editor ...etc...
		base: 	commit d1c314a "Adds new test cases for the object editor and fixes some ...etc...
	Receiver's instance variables: 
		diffs: 	()
		leftArtifacts: 	('repository/BaselineOfHome.package'->a SquotLiveArtifact 'repos...etc...
		rightArtifacts: 	(''->a LBGitRecordedFilesArtifact(On commit: 'Adds object edito...etc...
		baseArtifacts: 	(''->a LBGitRecordedFilesArtifact(On commit: 'Adds new test case...etc...
		fromBaseToIncoming: 	nil
		fromBaseToExisting: 	nil
		leftLoadOrder: 	()
		rightLoadOrder: 	()
		baseLoadOrder: 	()
		loadOrderPatch: 	nil

SquotWorkingCopy>>mergeVersionInteractively:ifCanceled:
	Receiver: Home
	Arguments and temporary variables: 
		aVersion: 	commit e2d1828 "Adds object editor to readme [ci skip]"
		cancelBlock: 	[closure] in SquitBrowser>>mergeVersionIntoActiveBranch:ifCanceled:...etc...
		mergeBases: 	(commit d1c314a "Adds new test cases for the object editor and fixe...etc...
		mergePatch: 	nil
		fastForwardPossible: 	#(true)
	Receiver's instance variables: 
		name: 	'Home'
		store: 	a SquotImageStore
		repository: 	a SquitRepository
		loadedHistorian: 	a SquitHistorian('refs/heads/master')
		previousVersionId: 	nil
		previousSnapshot: 	nil
		previouslySavedArtifacts: 	('repository/Home.package'->a SquotArtifact('reposito...etc...
		shouldStoreMetadata: 	nil
		additionalParents: 	nil
		lastLoadedHistorian: 	a SquitHistorian('refs/meta/squot-loaded-home.1815.image')...etc...
		snapshotBlock: 	nil
		loadedVersion: 	commit d1c314a "Adds new test cases for the object editor and fi...etc...
		newVersionMessage: 	nil

SquitBrowser>>mergeVersionIntoActiveBranch:ifCanceled:
	Receiver: a SquitBrowser
	Arguments and temporary variables: 
		mergeHeadCommit: 	commit e2d1828 "Adds object editor to readme [ci skip]"
		cancelBlock: 	[closure] in [] in SquitBrowser>>actionPull
		selectedProject: 	Home
	Receiver's instance variables: 
		dependents: 	(a PluggableSystemWindow<Git Browser: Home (master)>(1468935) a PluggableButtonMorphPlus...etc...
		projectIndex: 	10
		commitSelection: 	commit d1c314a "Adds new test cases for the object editor and ...etc...
		objectIndex: 	nil
		objectCache: 	{Recorded files: (repository/.filetree, scripts/build_images.sh, ....etc...
		commitForCache: 	commit d1c314a "Adds new test cases for the object editor and f...etc...
		timeOfLastListUpdate: 	3721473916120
		searchTerm: 	''
		offeredToAddFirstProject: 	true
		repositoryExists: 	true
		cachedCommitList: 	(commit d1c314a "Adds new test cases for the object editor an...etc...
		commitListBuildProcess: 	a Process in [] in BlockClosure>>newProcess
		selectedHistorian: 	a SquitHistorian('refs/heads/master')
		indexOfActiveHistorianInBranchList: 	3
		branchList: 	#('-- Branches --' 'develop' 'master' 'origin/codeZeilen-readme-upd...etc...
		commitToDiffAgainst: 	nil

[] in SquitBrowser>>actionPull
	Receiver: a SquitBrowser
	Arguments and temporary variables: 
<<error during printing>
	Receiver's instance variables: 
		dependents: 	(a PluggableSystemWindow<Git Browser: Home (master)>(1468935) a PluggableButtonMorphPlus...etc...
		projectIndex: 	10
		commitSelection: 	commit d1c314a "Adds new test cases for the object editor and ...etc...
		objectIndex: 	nil
		objectCache: 	{Recorded files: (repository/.filetree, scripts/build_images.sh, ....etc...
		commitForCache: 	commit d1c314a "Adds new test cases for the object editor and f...etc...
		timeOfLastListUpdate: 	3721473916120
		searchTerm: 	''
		offeredToAddFirstProject: 	true
		repositoryExists: 	true
		cachedCommitList: 	(commit d1c314a "Adds new test cases for the object editor an...etc...
		commitListBuildProcess: 	a Process in [] in BlockClosure>>newProcess
		selectedHistorian: 	a SquitHistorian('refs/heads/master')
		indexOfActiveHistorianInBranchList: 	3
		branchList: 	#('-- Branches --' 'develop' 'master' 'origin/codeZeilen-readme-upd...etc...
		commitToDiffAgainst: 	nil

BlockClosure>>on:do:
	Receiver: [closure] in SquitBrowser>>actionPull
	Arguments and temporary variables: 
		exceptionOrExceptionSet: 	SquotInitialLogMessageRequested
		handlerAction: 	[closure] in SquitBrowser>>actionPull
		handlerActive: 	true
	Receiver's instance variables: 
		outerContext: 	SquitBrowser>>actionPull
		startpc: 	273
		numArgs: 	0

SquitBrowser>>actionPull
	Receiver: a SquitBrowser
	Arguments and temporary variables: 
		gitRepository: 	a FileSystemGitRepository
		localHistorian: 	a SquitHistorian('refs/heads/master')
		localBranchName: 	'master'
		remoteName: 	'origin'
		repository: 	a SquitRepository
		remoteRef: 	'refs/heads/master'
		remoteTrackingHistorian: 	a SquitHistorian('refs/remotes/origin/master')
		remoteTrackingRef: 	'refs/remotes/origin/master'
		remoteUrl: 	'https://github.com/hpi-swa-lab/home-desktop-system.git'
		remoteVersion: 	commit e2d1828 "Adds object editor to readme [ci skip]"
		previousVersion: 	commit d1c314a "Adds new test cases for the object editor and ...etc...
	Receiver's instance variables: 
		dependents: 	(a PluggableSystemWindow<Git Browser: Home (master)>(1468935) a PluggableButtonMorphPlus...etc...
		projectIndex: 	10
		commitSelection: 	commit d1c314a "Adds new test cases for the object editor and ...etc...
		objectIndex: 	nil
		objectCache: 	{Recorded files: (repository/.filetree, scripts/build_images.sh, ....etc...
		commitForCache: 	commit d1c314a "Adds new test cases for the object editor and f...etc...
		timeOfLastListUpdate: 	3721473916120
		searchTerm: 	''
		offeredToAddFirstProject: 	true
		repositoryExists: 	true
		cachedCommitList: 	(commit d1c314a "Adds new test cases for the object editor an...etc...
		commitListBuildProcess: 	a Process in [] in BlockClosure>>newProcess
		selectedHistorian: 	a SquitHistorian('refs/heads/master')
		indexOfActiveHistorianInBranchList: 	3
		branchList: 	#('-- Branches --' 'develop' 'master' 'origin/codeZeilen-readme-upd...etc...
		commitToDiffAgainst: 	nil

PluggableButtonMorphPlus(PluggableButtonMorph)>>performAction
	Receiver: a PluggableButtonMorphPlus(2149399)
	Arguments and temporary variables: 

	Receiver's instance variables: 
		bounds: 	614@627 corner: 685@648
		owner: 	a PluggablePanelMorph(619268)
		submorphs: 	#()
		fullBounds: 	614@627 corner: 685@648
		color: 	(Color r: 0.933 g: 0.909 b: 0.835)
		extension: 	a MorphExtension (52940) [balloonText]  [other:  (styleContext -> a ...etc...
		model: 	a SquitBrowser
		label: 	'Pull'
		font: 	a StrikeFont(Bitmap DejaVu Sans 7 10)
		getStateSelector: 	nil
		actionSelector: 	#actionPull
		getLabelSelector: 	nil
		getMenuSelector: 	nil
		shortcutCharacter: 	nil
		askBeforeChanging: 	false
		triggerOnMouseDown: 	false
		offColor: 	(Color r: 0.933 g: 0.909 b: 0.835)
		onColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		feedbackColor: 	(Color r: 0.632 g: 0.617 b: 0.566)
		showSelectionFeedback: 	nil
		allButtons: 	{a PluggableButtonMorphPlus(2545767) . a PluggableButtonMorphPlus(2...etc...
		arguments: 	nil
		argumentsProvider: 	nil
		argumentsSelector: 	nil
		style: 	nil
		hoverColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		borderColor: 	(Color r: 0.576 g: 0.63 b: 0.63)
		textColor: 	(Color r: 0.027 g: 0.211 b: 0.258)
		labelOffset: 	0@0
		wantsGradient: 	nil
		enabled: 	true
		action: 	nil
		getColorSelector: 	nil
		getEnabledSelector: 	#hasBranchSelection
		updateMap: 	nil
		disabledColor: 	Color transparent
		disabledTextColor: 	(Color r: 0.576 g: 0.63 b: 0.63)

PluggableButtonMorphPlus>>performAction
	Receiver: a PluggableButtonMorphPlus(2149399)
	Arguments and temporary variables: 

	Receiver's instance variables: 
		bounds: 	614@627 corner: 685@648
		owner: 	a PluggablePanelMorph(619268)
		submorphs: 	#()
		fullBounds: 	614@627 corner: 685@648
		color: 	(Color r: 0.933 g: 0.909 b: 0.835)
		extension: 	a MorphExtension (52940) [balloonText]  [other:  (styleContext -> a ...etc...
		model: 	a SquitBrowser
		label: 	'Pull'
		font: 	a StrikeFont(Bitmap DejaVu Sans 7 10)
		getStateSelector: 	nil
		actionSelector: 	#actionPull
		getLabelSelector: 	nil
		getMenuSelector: 	nil
		shortcutCharacter: 	nil
		askBeforeChanging: 	false
		triggerOnMouseDown: 	false
		offColor: 	(Color r: 0.933 g: 0.909 b: 0.835)
		onColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		feedbackColor: 	(Color r: 0.632 g: 0.617 b: 0.566)
		showSelectionFeedback: 	nil
		allButtons: 	{a PluggableButtonMorphPlus(2545767) . a PluggableButtonMorphPlus(2...etc...
		arguments: 	nil
		argumentsProvider: 	nil
		argumentsSelector: 	nil
		style: 	nil
		hoverColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		borderColor: 	(Color r: 0.576 g: 0.63 b: 0.63)
		textColor: 	(Color r: 0.027 g: 0.211 b: 0.258)
		labelOffset: 	0@0
		wantsGradient: 	nil
		enabled: 	true
		action: 	nil
		getColorSelector: 	nil
		getEnabledSelector: 	#hasBranchSelection
		updateMap: 	nil
		disabledColor: 	Color transparent
		disabledTextColor: 	(Color r: 0.576 g: 0.63 b: 0.63)

[] in PluggableButtonMorphPlus(PluggableButtonMorph)>>mouseUp:
	Receiver: a PluggableButtonMorphPlus(2149399)
	Arguments and temporary variables: 
		evt: 	a PluggableButtonMorphPlus(2149399)
		m: 	[664@639 mouseUp ( red ) 448858406]
	Receiver's instance variables: 
		bounds: 	614@627 corner: 685@648
		owner: 	a PluggablePanelMorph(619268)
		submorphs: 	#()
		fullBounds: 	614@627 corner: 685@648
		color: 	(Color r: 0.933 g: 0.909 b: 0.835)
		extension: 	a MorphExtension (52940) [balloonText]  [other:  (styleContext -> a ...etc...
		model: 	a SquitBrowser
		label: 	'Pull'
		font: 	a StrikeFont(Bitmap DejaVu Sans 7 10)
		getStateSelector: 	nil
		actionSelector: 	#actionPull
		getLabelSelector: 	nil
		getMenuSelector: 	nil
		shortcutCharacter: 	nil
		askBeforeChanging: 	false
		triggerOnMouseDown: 	false
		offColor: 	(Color r: 0.933 g: 0.909 b: 0.835)
		onColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		feedbackColor: 	(Color r: 0.632 g: 0.617 b: 0.566)
		showSelectionFeedback: 	nil
		allButtons: 	{a PluggableButtonMorphPlus(2545767) . a PluggableButtonMorphPlus(2...etc...
		arguments: 	nil
		argumentsProvider: 	nil
		argumentsSelector: 	nil
		style: 	nil
		hoverColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		borderColor: 	(Color r: 0.576 g: 0.63 b: 0.63)
		textColor: 	(Color r: 0.027 g: 0.211 b: 0.258)
		labelOffset: 	0@0
		wantsGradient: 	nil
		enabled: 	true
		action: 	nil
		getColorSelector: 	nil
		getEnabledSelector: 	#hasBranchSelection
		updateMap: 	nil
		disabledColor: 	Color transparent
		disabledTextColor: 	(Color r: 0.576 g: 0.63 b: 0.63)

Array(SequenceableCollection)>>do:
	Receiver: {a PluggableButtonMorphPlus(2545767) . a PluggableButtonMorphPlus(2149399) . a PluggableButtonMorphPlus...etc...
	Arguments and temporary variables: 
		aBlock: 	[closure] in PluggableButtonMorphPlus(PluggableButtonMorph)>>mouseUp:
		index: 	2
		indexLimiT: 	8
	Receiver's instance variables: 
{a PluggableButtonMorphPlus(2545767) . a PluggableButtonMorphPlus(2149399) . a PluggableButtonMorphPlus...etc...

PluggableButtonMorphPlus(PluggableButtonMorph)>>mouseUp:
	Receiver: a PluggableButtonMorphPlus(2149399)
	Arguments and temporary variables: 
		evt: 	[664@639 mouseUp ( red ) 448858406]
	Receiver's instance variables: 
		bounds: 	614@627 corner: 685@648
		owner: 	a PluggablePanelMorph(619268)
		submorphs: 	#()
		fullBounds: 	614@627 corner: 685@648
		color: 	(Color r: 0.933 g: 0.909 b: 0.835)
		extension: 	a MorphExtension (52940) [balloonText]  [other:  (styleContext -> a ...etc...
		model: 	a SquitBrowser
		label: 	'Pull'
		font: 	a StrikeFont(Bitmap DejaVu Sans 7 10)
		getStateSelector: 	nil
		actionSelector: 	#actionPull
		getLabelSelector: 	nil
		getMenuSelector: 	nil
		shortcutCharacter: 	nil
		askBeforeChanging: 	false
		triggerOnMouseDown: 	false
		offColor: 	(Color r: 0.933 g: 0.909 b: 0.835)
		onColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		feedbackColor: 	(Color r: 0.632 g: 0.617 b: 0.566)
		showSelectionFeedback: 	nil
		allButtons: 	{a PluggableButtonMorphPlus(2545767) . a PluggableButtonMorphPlus(2...etc...
		arguments: 	nil
		argumentsProvider: 	nil
		argumentsSelector: 	nil
		style: 	nil
		hoverColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		borderColor: 	(Color r: 0.576 g: 0.63 b: 0.63)
		textColor: 	(Color r: 0.027 g: 0.211 b: 0.258)
		labelOffset: 	0@0
		wantsGradient: 	nil
		enabled: 	true
		action: 	nil
		getColorSelector: 	nil
		getEnabledSelector: 	#hasBranchSelection
		updateMap: 	nil
		disabledColor: 	Color transparent
		disabledTextColor: 	(Color r: 0.576 g: 0.63 b: 0.63)

PluggableButtonMorphPlus(Morph)>>handleMouseUp:
	Receiver: a PluggableButtonMorphPlus(2149399)
	Arguments and temporary variables: 
		anEvent: 	[664@639 mouseUp ( red ) 448858406]
	Receiver's instance variables: 
		bounds: 	614@627 corner: 685@648
		owner: 	a PluggablePanelMorph(619268)
		submorphs: 	#()
		fullBounds: 	614@627 corner: 685@648
		color: 	(Color r: 0.933 g: 0.909 b: 0.835)
		extension: 	a MorphExtension (52940) [balloonText]  [other:  (styleContext -> a ...etc...
		model: 	a SquitBrowser
		label: 	'Pull'
		font: 	a StrikeFont(Bitmap DejaVu Sans 7 10)
		getStateSelector: 	nil
		actionSelector: 	#actionPull
		getLabelSelector: 	nil
		getMenuSelector: 	nil
		shortcutCharacter: 	nil
		askBeforeChanging: 	false
		triggerOnMouseDown: 	false
		offColor: 	(Color r: 0.933 g: 0.909 b: 0.835)
		onColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		feedbackColor: 	(Color r: 0.632 g: 0.617 b: 0.566)
		showSelectionFeedback: 	nil
		allButtons: 	{a PluggableButtonMorphPlus(2545767) . a PluggableButtonMorphPlus(2...etc...
		arguments: 	nil
		argumentsProvider: 	nil
		argumentsSelector: 	nil
		style: 	nil
		hoverColor: 	(Color r: 0.833 g: 0.811 b: 0.745)
		borderColor: 	(Color r: 0.576 g: 0.63 b: 0.63)
		textColor: 	(Color r: 0.027 g: 0.211 b: 0.258)
		labelOffset: 	0@0
		wantsGradient: 	nil
		enabled: 	true
		action: 	nil
		getColorSelector: 	nil
		getEnabledSelector: 	#hasBranchSelection
		updateMap: 	nil
		disabledColor: 	Color transparent
		disabledTextColor: 	(Color r: 0.576 g: 0.63 b: 0.63)

--- The full stack ---
LBGitFileListDiff(Object)>>doesNotUnderstand: #isAddition
SquotPatchBuilder>>addDiff:
SquotPatchBuilder>>diffPath:from:to:
[] in SquitVersion>>patchRelativeToBaseVersion:
Array(SequenceableCollection)>>do:
SquitVersion>>patchRelativeToBaseVersion:
SquitVersion>>patchRelativeToBase:
SquotMergePatchBuilder>>patchFrom:to:base:
SquotWorkingCopy>>mergeVersionInteractively:ifCanceled:
SquitBrowser>>mergeVersionIntoActiveBranch:ifCanceled:
[] in SquitBrowser>>actionPull
BlockClosure>>on:do:
SquitBrowser>>actionPull
PluggableButtonMorphPlus(PluggableButtonMorph)>>performAction
PluggableButtonMorphPlus>>performAction
[] in PluggableButtonMorphPlus(PluggableButtonMorph)>>mouseUp:
Array(SequenceableCollection)>>do:
PluggableButtonMorphPlus(PluggableButtonMorph)>>mouseUp:
PluggableButtonMorphPlus(Morph)>>handleMouseUp:
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
MouseButtonEvent>>sentTo:
PluggableButtonMorphPlus(Morph)>>handleEvent:
PluggableButtonMorphPlus(Morph)>>handleFocusEvent:
MorphicEventDispatcher>>doHandlingForFocusEvent:with:
MorphicEventDispatcher>>dispatchFocusEvent:with:
PluggableButtonMorphPlus(Morph)>>processFocusEvent:using:
PluggableButtonMorphPlus(Morph)>>processFocusEvent:
[] in [] in [] in HandMorph>>sendFocusEvent:to:clear:
BlockClosure>>ensure:
MouseButtonEvent(MorphicEvent)>>becomeActiveDuring:
[] in [] in HandMorph>>sendFocusEvent:to:clear:
BlockClosure>>ensure:
HandMorph>>becomeActiveDuring:
[] in HandMorph>>sendFocusEvent:to:clear:
BlockClosure>>ensure:
PasteUpMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
HandMorph>>processEvents
[] in WorldState>>doOneCycleNowFor:
Array(SequenceableCollection)>>do:
WorldState>>handsDo:
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
PasteUpMorph>>doOneCycle
[] in MorphicProject>>spawnNewProcess
[] in BlockClosure>>newProcess

**Comment by LeonBein** [comment]
I was able to reproduce the error on local ci, it occured because I was developing on an older version on squot.
I wrote and uploaded a fix, but there seems to be an error on travis (could not access squeaksource?), so I will not yet close this issue.

**Comment by LeonBein** [comment]
As Squeaksource is accessible again, I restarted the travis build and it passed, you should not be having this issue any more.
